/**
 * Service Manager API
 * Service process automation project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ServiceManagerApi);
  }
}(this, function(expect, ServiceManagerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ServiceManagerApi.EnApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EnApi', function() {
    describe('enApiServiceOrdersCreate', function() {
      it('should call enApiServiceOrdersCreate successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersCreate
        //instance.enApiServiceOrdersCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enApiServiceOrdersDestroy', function() {
      it('should call enApiServiceOrdersDestroy successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersDestroy
        //instance.enApiServiceOrdersDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enApiServiceOrdersList', function() {
      it('should call enApiServiceOrdersList successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersList
        //instance.enApiServiceOrdersList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enApiServiceOrdersPartialUpdate', function() {
      it('should call enApiServiceOrdersPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersPartialUpdate
        //instance.enApiServiceOrdersPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enApiServiceOrdersRetrieve', function() {
      it('should call enApiServiceOrdersRetrieve successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersRetrieve
        //instance.enApiServiceOrdersRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enApiServiceOrdersUpdate', function() {
      it('should call enApiServiceOrdersUpdate successfully', function(done) {
        //uncomment below and update the code to test enApiServiceOrdersUpdate
        //instance.enApiServiceOrdersUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
