/**
 * Service Manager API
 * Service process automation project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PlaceOfServiceEnum.
* @enum {}
* @readonly
*/
export default class PlaceOfServiceEnum {
    
        /**
         * value: "Customer office"
         * @const
         */
        "Customer office" = "Customer office";

    
        /**
         * value: "Brought in"
         * @const
         */
        "Brought in" = "Brought in";

    

    /**
    * Returns a <code>PlaceOfServiceEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PlaceOfServiceEnum} The enum <code>PlaceOfServiceEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

