/**
 * Service Manager API
 * Service process automation project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import PatchedServiceOrderHeader from './model/PatchedServiceOrderHeader';
import PlaceOfServiceEnum from './model/PlaceOfServiceEnum';
import ServiceOrderHeader from './model/ServiceOrderHeader';
import EnApi from './api/EnApi';


/**
* Service process automation project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ServiceManagerApi = require('index'); // See note below*.
* var xxxSvc = new ServiceManagerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ServiceManagerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ServiceManagerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ServiceManagerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The PatchedServiceOrderHeader model constructor.
     * @property {module:model/PatchedServiceOrderHeader}
     */
    PatchedServiceOrderHeader,

    /**
     * The PlaceOfServiceEnum model constructor.
     * @property {module:model/PlaceOfServiceEnum}
     */
    PlaceOfServiceEnum,

    /**
     * The ServiceOrderHeader model constructor.
     * @property {module:model/ServiceOrderHeader}
     */
    ServiceOrderHeader,

    /**
    * The EnApi service constructor.
    * @property {module:api/EnApi}
    */
    EnApi
};
