# Generated by Django 4.1.1 on 2023-11-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_servicerequest_order_type"),
        ("service_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrequest",
            name="service_request",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.servicerequest",
                verbose_name="service_request",
            ),
            preserve_default=False,
        ),
    ]
