# Generated by Django 4.1.1 on 2022-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_assetcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customertype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
