# Generated by Django 4.1.1 on 2022-10-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerasset',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerdepartment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerrepresentative',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
