# Generated by Django 4.1.1 on 2022-11-03 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customerasset_active_customerdepartment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepresentative',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
