# Generated by Django 4.1.1 on 2022-12-17 23:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import service_manager.customers.validators


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0006_alter_asset_brand_alter_asset_category_and_more"),
        ("customers", "0008_auto_20221124_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    service_manager.customers.validators.phone_number_validator
                ],
                verbose_name="phone_number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.customertype",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    service_manager.customers.validators.numbers_only_validator
                ],
                verbose_name="vat",
            ),
        ),
        migrations.AlterField(
            model_name="customerasset",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.asset",
                verbose_name="asset",
            ),
        ),
        migrations.AlterField(
            model_name="customerasset",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerasset",
            name="product_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="serial_number"
            ),
        ),
        migrations.AlterField(
            model_name="customerasset",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="serial_number"
            ),
        ),
        migrations.AlterField(
            model_name="customerdepartment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerdepartment",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="customerrepresentative",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrepresentative",
            name="email_address",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator],
                verbose_name="email_address",
            ),
        ),
        migrations.AlterField(
            model_name="customerrepresentative",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="first_name"),
        ),
        migrations.AlterField(
            model_name="customerrepresentative",
            name="last_name",
            field=models.CharField(max_length=20, verbose_name="last_name"),
        ),
        migrations.AlterField(
            model_name="customerrepresentative",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    service_manager.customers.validators.phone_number_validator
                ],
                verbose_name="phone_number",
            ),
        ),
    ]
