# Generated by Django 4.1.1 on 2022-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_customer_phone_number_alter_customer_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer", options={"ordering": ("is_regular_customer", "name")},
        ),
        migrations.AddField(
            model_name="customer",
            name="has_subscription",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_regular_customer",
            field=models.BooleanField(default=0),
        ),
    ]
