# Generated by Django 4.1.1 on 2023-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_alter_customer_options_customer_has_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerasset",
            name="inventory_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="inventory_number"
            ),
        ),
    ]
