# Generated by Django 4.1.1 on 2023-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_customerasset_inventory_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerasset",
            name="product_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="product_number"
            ),
        ),
    ]
