# Generated by Django 4.1.1 on 2023-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_alter_customerasset_product_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerasset",
            name="location",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="location"
            ),
        ),
    ]
