# Generated by Django 4.1.1 on 2023-01-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0013_customerasset_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="has_subscription",
            field=models.BooleanField(default=0, verbose_name="has subscription"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_regular_customer",
            field=models.BooleanField(default=0, verbose_name="is regular customer"),
        ),
    ]
