# Generated by Django 4.1.1 on 2023-03-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0014_alter_customer_has_subscription_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ("-is_regular_customer", "-has_subscription", "name")},
        ),
    ]
