# Generated by Django 4.1.1 on 2023-04-21 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0015_alter_customer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email_address",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator],
                verbose_name="email_address",
            ),
        ),
    ]
