# Generated by Django 4.1.1 on 2022-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_asset_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
