# Generated by Django 4.1.1 on 2022-10-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_asset_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
