# Generated by Django 4.1.1 on 2022-12-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "master_data",
            "0005_brand_active_customertype_active_material_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.brand",
                verbose_name="brand",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.assetcategory",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="model_name",
            field=models.CharField(max_length=100, verbose_name="model_name"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="model_number",
            field=models.CharField(max_length=20, verbose_name="model_number"),
        ),
        migrations.AlterField(
            model_name="assetcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="customertype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.materialcategory",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="material",
            name="price",
            field=models.FloatField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="materialcategory",
            name="name",
            field=models.CharField(max_length=20, verbose_name="name"),
        ),
    ]
