# Generated by Django 4.1.1 on 2023-01-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0006_alter_asset_brand_alter_asset_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
