# Generated by Django 4.1.1 on 2024-05-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_sla"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialcategory", options={"ordering": ["name"]},
        ),
    ]
