# Generated by Django 4.1.1 on 2022-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_id_alter_profile_app_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
