# Generated by Django 4.1.1 on 2024-06-19 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0017_alter_customer_options_and_more"),
        ("accounts", "0004_alter_appuser_email_alter_profile_app_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer id",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="is customer"),
        ),
    ]
