# Generated by Django 4.1.1 on 2022-10-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('master_data', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_serviced', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('serviced_on', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='accounts.profile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('customer_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customerasset')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerdepartment')),
                ('handed_over_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handed_by_customer_representative', to='customers.customerrepresentative')),
                ('handed_over_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handed_to_customer_representative', to='customers.customerrepresentative')),
                ('serviced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_by', to='accounts.profile')),
            ],
            options={
                'db_table': 'main_service_order_header',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceorderheader')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('discount', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.material')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceorderheader')),
            ],
            options={
                'db_table': 'main_service_order_detail',
            },
        ),
    ]
