# Generated by Django 4.1.1 on 2022-12-17 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0009_alter_customer_phone_number_alter_customer_type_and_more"),
        ("master_data", "0006_alter_asset_brand_alter_asset_category_and_more"),
        ("main", "0009_serviceorderheader_send_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderdetail",
            name="discount",
            field=models.FloatField(verbose_name="discount"),
        ),
        migrations.AlterField(
            model_name="serviceorderdetail",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.material",
                verbose_name="material",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderdetail",
            name="quantity",
            field=models.FloatField(verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="serviceorderdetail",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.serviceorderheader",
                verbose_name="service_order",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="accepted_by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="completed_by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="completed_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed_on"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="customer_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customerasset",
                verbose_name="customer_asset",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customerdepartment",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="handed_over_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handed_by_customer_representative",
                to="customers.customerrepresentative",
                verbose_name="handed_over_by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="handed_over_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handed_to_customer_representative",
                to="customers.customerrepresentative",
                verbose_name="handed_over_to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is_completed"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="is_serviced",
            field=models.BooleanField(default=False, verbose_name="is_serviced"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="problem_description",
            field=models.TextField(verbose_name="problem_description"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="send_emails",
            field=models.BooleanField(default=True, verbose_name="send_emails"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="serviced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviced_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="serviced_by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="serviced_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="serviced_on"
            ),
        ),
        migrations.AlterField(
            model_name="serviceordernote",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceordernote",
            name="note",
            field=models.TextField(verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="serviceordernote",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.serviceorderheader",
                verbose_name="service_order",
            ),
        ),
    ]
