# Generated by Django 4.1.1 on 2023-01-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_serviceorderdetail_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderheader",
            name="packaging",
            field=models.TextField(blank=True, null=True, verbose_name="packaging"),
        ),
    ]
