# Generated by Django 4.1.1 on 2023-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_serviceorderheader_packaging"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderheader",
            name="packaging",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="packaging"
            ),
        ),
    ]
