# Generated by Django 4.1.1 on 2023-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_serviceorderheader_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderheader",
            name="place_of_service",
            field=models.CharField(
                choices=[
                    ("customer office", "Customer office"),
                    ("brought in", "Brought in"),
                ],
                default="customer office",
                max_length=20,
            ),
        ),
    ]
