# Generated by Django 4.1.1 on 2023-01-18 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_alter_customerasset_product_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_serviceorderheader_place_of_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderheader",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="accepted by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="completed by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="completed_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed on"
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="customer_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customerasset",
                verbose_name="customer asset",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="handed_over_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handed_by_customer_representative",
                to="customers.customerrepresentative",
                verbose_name="handed over by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="handed_over_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="handed_to_customer_representative",
                to="customers.customerrepresentative",
                verbose_name="handed over to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="is_serviced",
            field=models.BooleanField(default=False, verbose_name="is serviced"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="place_of_service",
            field=models.CharField(
                choices=[
                    ("Customer office", "Customer office"),
                    ("Brought in", "Brought in"),
                ],
                default="Brought in",
                max_length=20,
                verbose_name="place of service",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="problem_description",
            field=models.TextField(verbose_name="problem description"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="send_emails",
            field=models.BooleanField(default=True, verbose_name="send emails"),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="serviced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviced_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="serviced by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderheader",
            name="serviced_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="serviced on"
            ),
        ),
    ]
