# Generated by Django 4.1.1 on 2023-01-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_sla"),
        ("main", "0015_sla_serviceorderheader_service_level_agreement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderheader",
            name="service_level_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_level_agreement",
                to="master_data.sla",
                verbose_name="service_level_agreement",
            ),
        ),
        migrations.DeleteModel(name="SLA",),
    ]
