# Generated by Django 4.1.1 on 2023-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_serviceorderheader_service_level_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderheader",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
