# Generated by Django 4.1.1 on 2023-02-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_serviceorderheader_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderheader",
            name="send_emails",
            field=models.BooleanField(default=False, verbose_name="send emails"),
        ),
    ]
