# Generated by Django 4.1.1 on 2023-03-21 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0018_alter_serviceorderheader_send_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderdetail",
            name="discount",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="discount",
            ),
        ),
        migrations.CreateModel(
            name="CustomerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("notified_on", models.DateTimeField(verbose_name="notified_on")),
                (
                    "notification_method",
                    models.CharField(
                        choices=[(1, "By phone"), (2, "By email")],
                        default=1,
                        max_length=2,
                        verbose_name="notification_method",
                    ),
                ),
                ("comment", models.CharField(max_length=100, verbose_name="comment")),
                (
                    "service_order_current_status",
                    models.CharField(
                        max_length=20, verbose_name="service_order_current_status"
                    ),
                ),
                (
                    "notified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serviceorderheader",
                        verbose_name="service_order",
                    ),
                ),
            ],
            options={"ordering": ("-created_on",),},
        ),
    ]
