# Generated by Django 4.1.1 on 2023-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_serviceorderdetail_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customernotification",
            name="comment",
            field=models.CharField(max_length=100, null=True, verbose_name="comment"),
        ),
    ]
