# Generated by Django 4.1.1 on 2023-04-24 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service_manager.customers.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0016_alter_customer_email_address"),
        ("main", "0020_alter_customernotification_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "problem_description",
                    models.CharField(
                        max_length=255, verbose_name="problem_description"
                    ),
                ),
                (
                    "requestor_name",
                    models.CharField(max_length=100, verbose_name="requestor_name"),
                ),
                (
                    "requestor_phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            service_manager.customers.validators.phone_number_validator
                        ],
                        verbose_name="requestor_phone_number",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(max_length=100, verbose_name="resolution"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (1, "New"),
                            (2, "In progress"),
                            (3, "Handled"),
                            (4, "Closed"),
                            (5, "Rejected"),
                        ],
                        default=1,
                        max_length=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_accepted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="accepted by",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="closed_by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handled_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handled_by",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.serviceorderheader",
                        verbose_name="service_order",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
