# Generated by Django 4.1.1 on 2023-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_servicerequest_closed_on_servicerequest_handled_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    (1, "New"),
                    (2, "In progress"),
                    (3, "Resolved"),
                    (4, "Closed"),
                    (5, "Rejected"),
                ],
                default=1,
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
