# Generated by Django 4.1.1 on 2023-11-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_servicerequest_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicerequest", options={"ordering": ("status", "-created_on")},
        ),
    ]
