# Generated by Django 4.1.1 on 2023-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_servicerequest_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="order_type",
            field=models.IntegerField(
                choices=[(1, "Service"), (2, "Delivery")],
                default=1,
                verbose_name="order type",
            ),
        ),
    ]
