# Generated by Django 4.1.1 on 2024-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_servicerequest_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="resolution",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="resolution"
            ),
        ),
    ]
