# Generated by Django 4.1.1 on 2024-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_servicerequest_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "New"),
                    ("2", "In progress"),
                    ("3", "Resolved"),
                    ("4", "Closed"),
                    ("5", "Rejected"),
                ],
                default="1",
                max_length=1,
                verbose_name="status",
            ),
        ),
    ]
