# Generated by Django 4.1.1 on 2022-10-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceorderdetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceorderheader',
            table=None,
        ),
    ]
