# Generated by Django 4.1.1 on 2022-10-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_serviceorderdetail_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderheader',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceorderheader',
            name='serviced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
