# Generated by Django 4.1.1 on 2022-09-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_asset_assetcategory_brand_customerdepartment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerasset',
            table='customer_assets',
        ),
    ]
