# Generated by Django 4.1.1 on 2022-10-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerasset_table_and_more'),
        ('main', '0005_serviceorderheader_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderheader',
            name='handed_over_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handed_by_customer_representative', to='customers.customerrepresentative'),
        ),
    ]
