# Generated by Django 4.1.1 on 2022-09-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customerasset_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
    ]
