# Generated by Django 4.1.1 on 2022-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_serviceorderheader_handed_over_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderheader',
            name='problem_description',
            field=models.TextField(default='some text'),
            preserve_default=False,
        ),
    ]
