# Generated by Django 4.1.1 on 2022-09-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_materialcategory_serviceorderheader_material'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceorderheader',
            table='main_service_order_header',
        ),
    ]
