# Generated by Django 4.1.1 on 2022-09-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_serviceorderheader_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('discount', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceorderheader')),
            ],
            options={
                'db_table': 'main_service_order_detail',
            },
        ),
    ]
