# Generated by Django 4.1.1 on 2022-09-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_serviceorderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_category',
            new_name='category',
        ),
        migrations.CreateModel(
            name='ServiceOrderNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.serviceorderheader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
