# Generated by Django 4.1.1 on 2022-09-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_asset_category_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='main.employee'),
        ),
    ]
