# Generated by Django 4.1.1 on 2022-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_role_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='main.role'),
        ),
    ]
