# Generated by Django 4.1.1 on 2022-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_role_employee_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(to='main.role'),
        ),
    ]
