# Generated by Django 4.1.1 on 2022-09-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderheader',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='main.employee'),
        ),
        migrations.AlterField(
            model_name='serviceorderheader',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customerdepartment'),
        ),
        migrations.AlterField(
            model_name='serviceorderheader',
            name='serviced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_by', to='main.employee'),
        ),
    ]
