# Generated by Django 4.1.1 on 2022-09-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_serviceorderheader_completed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorderheader',
            name='asset',
        ),
    ]
