# Generated by Django 4.1.1 on 2022-09-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_serviceorderheader_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderheader',
            name='customer_asset',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.customerasset'),
            preserve_default=False,
        ),
    ]
