# Generated by Django 4.1.1 on 2022-09-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_serviceorderheader_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderheader',
            name='customer_representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.customerrepresentative'),
            preserve_default=False,
        ),
    ]
