# Generated by Django 4.1.1 on 2022-09-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
