# Generated by Django 4.1.1 on 2022-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_employee_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderheader',
            name='is_serviced',
            field=models.BooleanField(default=False),
        ),
    ]
