# Generated by Django 4.1.1 on 2022-09-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_employee_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceOrderNode',
            new_name='ServiceOrderNote',
        ),
    ]
