# Generated by Django 4.1.1 on 2022-10-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0026_alter_assetcategory_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderheader',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='serviceorderheader',
            name='serviced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviced_by', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='serviceordernote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
