/**
 * Service Manager API
 * Service process automation project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PlaceOfServiceEnum from './PlaceOfServiceEnum';

/**
 * The PatchedServiceOrderHeader model module.
 * @module model/PatchedServiceOrderHeader
 * @version 1.0.0
 */
class PatchedServiceOrderHeader {
    /**
     * Constructs a new <code>PatchedServiceOrderHeader</code>.
     * @alias module:model/PatchedServiceOrderHeader
     */
    constructor() { 
        
        PatchedServiceOrderHeader.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedServiceOrderHeader</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedServiceOrderHeader} obj Optional instance to populate.
     * @return {module:model/PatchedServiceOrderHeader} The populated <code>PatchedServiceOrderHeader</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedServiceOrderHeader();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_on')) {
                obj['created_on'] = ApiClient.convertToType(data['created_on'], 'Date');
            }
            if (data.hasOwnProperty('updated_on')) {
                obj['updated_on'] = ApiClient.convertToType(data['updated_on'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('problem_description')) {
                obj['problem_description'] = ApiClient.convertToType(data['problem_description'], 'String');
            }
            if (data.hasOwnProperty('is_serviced')) {
                obj['is_serviced'] = ApiClient.convertToType(data['is_serviced'], 'Boolean');
            }
            if (data.hasOwnProperty('is_completed')) {
                obj['is_completed'] = ApiClient.convertToType(data['is_completed'], 'Boolean');
            }
            if (data.hasOwnProperty('serviced_on')) {
                obj['serviced_on'] = ApiClient.convertToType(data['serviced_on'], 'Date');
            }
            if (data.hasOwnProperty('completed_on')) {
                obj['completed_on'] = ApiClient.convertToType(data['completed_on'], 'Date');
            }
            if (data.hasOwnProperty('send_emails')) {
                obj['send_emails'] = ApiClient.convertToType(data['send_emails'], 'Boolean');
            }
            if (data.hasOwnProperty('packaging')) {
                obj['packaging'] = ApiClient.convertToType(data['packaging'], 'String');
            }
            if (data.hasOwnProperty('place_of_service')) {
                obj['place_of_service'] = PlaceOfServiceEnum.constructFromObject(data['place_of_service']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], 'Number');
            }
            if (data.hasOwnProperty('customer_asset')) {
                obj['customer_asset'] = ApiClient.convertToType(data['customer_asset'], 'Number');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'Number');
            }
            if (data.hasOwnProperty('handed_over_by')) {
                obj['handed_over_by'] = ApiClient.convertToType(data['handed_over_by'], 'Number');
            }
            if (data.hasOwnProperty('accepted_by')) {
                obj['accepted_by'] = ApiClient.convertToType(data['accepted_by'], 'Number');
            }
            if (data.hasOwnProperty('serviced_by')) {
                obj['serviced_by'] = ApiClient.convertToType(data['serviced_by'], 'Number');
            }
            if (data.hasOwnProperty('completed_by')) {
                obj['completed_by'] = ApiClient.convertToType(data['completed_by'], 'Number');
            }
            if (data.hasOwnProperty('handed_over_to')) {
                obj['handed_over_to'] = ApiClient.convertToType(data['handed_over_to'], 'Number');
            }
            if (data.hasOwnProperty('service_level_agreement')) {
                obj['service_level_agreement'] = ApiClient.convertToType(data['service_level_agreement'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchedServiceOrderHeader</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchedServiceOrderHeader</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['problem_description'] && !(typeof data['problem_description'] === 'string' || data['problem_description'] instanceof String)) {
            throw new Error("Expected the field `problem_description` to be a primitive type in the JSON string but got " + data['problem_description']);
        }
        // ensure the json data is a string
        if (data['packaging'] && !(typeof data['packaging'] === 'string' || data['packaging'] instanceof String)) {
            throw new Error("Expected the field `packaging` to be a primitive type in the JSON string but got " + data['packaging']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PatchedServiceOrderHeader.prototype['id'] = undefined;

/**
 * @member {Date} created_on
 */
PatchedServiceOrderHeader.prototype['created_on'] = undefined;

/**
 * @member {Date} updated_on
 */
PatchedServiceOrderHeader.prototype['updated_on'] = undefined;

/**
 * @member {Boolean} active
 */
PatchedServiceOrderHeader.prototype['active'] = undefined;

/**
 * @member {String} problem_description
 */
PatchedServiceOrderHeader.prototype['problem_description'] = undefined;

/**
 * @member {Boolean} is_serviced
 */
PatchedServiceOrderHeader.prototype['is_serviced'] = undefined;

/**
 * @member {Boolean} is_completed
 */
PatchedServiceOrderHeader.prototype['is_completed'] = undefined;

/**
 * @member {Date} serviced_on
 */
PatchedServiceOrderHeader.prototype['serviced_on'] = undefined;

/**
 * @member {Date} completed_on
 */
PatchedServiceOrderHeader.prototype['completed_on'] = undefined;

/**
 * @member {Boolean} send_emails
 */
PatchedServiceOrderHeader.prototype['send_emails'] = undefined;

/**
 * @member {String} packaging
 */
PatchedServiceOrderHeader.prototype['packaging'] = undefined;

/**
 * @member {module:model/PlaceOfServiceEnum} place_of_service
 */
PatchedServiceOrderHeader.prototype['place_of_service'] = undefined;

/**
 * @member {String} slug
 */
PatchedServiceOrderHeader.prototype['slug'] = undefined;

/**
 * @member {Number} customer
 */
PatchedServiceOrderHeader.prototype['customer'] = undefined;

/**
 * @member {Number} customer_asset
 */
PatchedServiceOrderHeader.prototype['customer_asset'] = undefined;

/**
 * @member {Number} department
 */
PatchedServiceOrderHeader.prototype['department'] = undefined;

/**
 * @member {Number} handed_over_by
 */
PatchedServiceOrderHeader.prototype['handed_over_by'] = undefined;

/**
 * @member {Number} accepted_by
 */
PatchedServiceOrderHeader.prototype['accepted_by'] = undefined;

/**
 * @member {Number} serviced_by
 */
PatchedServiceOrderHeader.prototype['serviced_by'] = undefined;

/**
 * @member {Number} completed_by
 */
PatchedServiceOrderHeader.prototype['completed_by'] = undefined;

/**
 * @member {Number} handed_over_to
 */
PatchedServiceOrderHeader.prototype['handed_over_to'] = undefined;

/**
 * @member {Number} service_level_agreement
 */
PatchedServiceOrderHeader.prototype['service_level_agreement'] = undefined;






export default PatchedServiceOrderHeader;

